// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProtonMail/proton-bridge/v3/internal/services/userevents (interfaces: EventSubscriber,MessageEventHandler,LabelEventHandler,AddressEventHandler,RefreshEventHandler,UserEventHandler,UserUsedSpaceEventHandler)
//
// Generated by this command:
//
//	mockgen --package userevents github.com/ProtonMail/proton-bridge/v3/internal/services/userevents EventSubscriber,MessageEventHandler,LabelEventHandler,AddressEventHandler,RefreshEventHandler,UserEventHandler,UserUsedSpaceEventHandler
//

// Package userevents is a generated GoMock package.
package userevents

import (
	context "context"
	reflect "reflect"

	proton "github.com/ProtonMail/go-proton-api"
	gomock "go.uber.org/mock/gomock"
)

// MockEventSubscriber is a mock of EventSubscriber interface.
type MockEventSubscriber[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockEventSubscriberMockRecorder[T]
	isgomock struct{}
}

// MockEventSubscriberMockRecorder is the mock recorder for MockEventSubscriber.
type MockEventSubscriberMockRecorder[T any] struct {
	mock *MockEventSubscriber[T]
}

// NewMockEventSubscriber creates a new mock instance.
func NewMockEventSubscriber[T any](ctrl *gomock.Controller) *MockEventSubscriber[T] {
	mock := &MockEventSubscriber[T]{ctrl: ctrl}
	mock.recorder = &MockEventSubscriberMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSubscriber[T]) EXPECT() *MockEventSubscriberMockRecorder[T] {
	return m.recorder
}

// cancel mocks base method.
func (m *MockEventSubscriber[T]) cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "cancel")
}

// cancel indicates an expected call of cancel.
func (mr *MockEventSubscriberMockRecorder[T]) cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "cancel", reflect.TypeOf((*MockEventSubscriber[T])(nil).cancel))
}

// close mocks base method.
func (m *MockEventSubscriber[T]) close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "close")
}

// close indicates an expected call of close.
func (mr *MockEventSubscriberMockRecorder[T]) close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "close", reflect.TypeOf((*MockEventSubscriber[T])(nil).close))
}

// handle mocks base method.
func (m *MockEventSubscriber[T]) handle(arg0 context.Context, arg1 proton.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "handle", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// handle indicates an expected call of handle.
func (mr *MockEventSubscriberMockRecorder[T]) handle(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "handle", reflect.TypeOf((*MockEventSubscriber[T])(nil).handle), arg0, arg1)
}

// name mocks base method.
func (m *MockEventSubscriber[T]) name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "name")
	ret0, _ := ret[0].(string)
	return ret0
}

// name indicates an expected call of name.
func (mr *MockEventSubscriberMockRecorder[T]) name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "name", reflect.TypeOf((*MockEventSubscriber[T])(nil).name))
}

// MockMessageEventHandler is a mock of MessageEventHandler interface.
type MockMessageEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMessageEventHandlerMockRecorder
	isgomock struct{}
}

// MockMessageEventHandlerMockRecorder is the mock recorder for MockMessageEventHandler.
type MockMessageEventHandlerMockRecorder struct {
	mock *MockMessageEventHandler
}

// NewMockMessageEventHandler creates a new mock instance.
func NewMockMessageEventHandler(ctrl *gomock.Controller) *MockMessageEventHandler {
	mock := &MockMessageEventHandler{ctrl: ctrl}
	mock.recorder = &MockMessageEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageEventHandler) EXPECT() *MockMessageEventHandlerMockRecorder {
	return m.recorder
}

// HandleMessageEvents mocks base method.
func (m *MockMessageEventHandler) HandleMessageEvents(ctx context.Context, events []proton.MessageEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleMessageEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleMessageEvents indicates an expected call of HandleMessageEvents.
func (mr *MockMessageEventHandlerMockRecorder) HandleMessageEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessageEvents", reflect.TypeOf((*MockMessageEventHandler)(nil).HandleMessageEvents), ctx, events)
}

// MockLabelEventHandler is a mock of LabelEventHandler interface.
type MockLabelEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockLabelEventHandlerMockRecorder
	isgomock struct{}
}

// MockLabelEventHandlerMockRecorder is the mock recorder for MockLabelEventHandler.
type MockLabelEventHandlerMockRecorder struct {
	mock *MockLabelEventHandler
}

// NewMockLabelEventHandler creates a new mock instance.
func NewMockLabelEventHandler(ctrl *gomock.Controller) *MockLabelEventHandler {
	mock := &MockLabelEventHandler{ctrl: ctrl}
	mock.recorder = &MockLabelEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLabelEventHandler) EXPECT() *MockLabelEventHandlerMockRecorder {
	return m.recorder
}

// HandleLabelEvents mocks base method.
func (m *MockLabelEventHandler) HandleLabelEvents(ctx context.Context, events []proton.LabelEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleLabelEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleLabelEvents indicates an expected call of HandleLabelEvents.
func (mr *MockLabelEventHandlerMockRecorder) HandleLabelEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleLabelEvents", reflect.TypeOf((*MockLabelEventHandler)(nil).HandleLabelEvents), ctx, events)
}

// MockAddressEventHandler is a mock of AddressEventHandler interface.
type MockAddressEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAddressEventHandlerMockRecorder
	isgomock struct{}
}

// MockAddressEventHandlerMockRecorder is the mock recorder for MockAddressEventHandler.
type MockAddressEventHandlerMockRecorder struct {
	mock *MockAddressEventHandler
}

// NewMockAddressEventHandler creates a new mock instance.
func NewMockAddressEventHandler(ctrl *gomock.Controller) *MockAddressEventHandler {
	mock := &MockAddressEventHandler{ctrl: ctrl}
	mock.recorder = &MockAddressEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressEventHandler) EXPECT() *MockAddressEventHandlerMockRecorder {
	return m.recorder
}

// HandleAddressEvents mocks base method.
func (m *MockAddressEventHandler) HandleAddressEvents(ctx context.Context, events []proton.AddressEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAddressEvents", ctx, events)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleAddressEvents indicates an expected call of HandleAddressEvents.
func (mr *MockAddressEventHandlerMockRecorder) HandleAddressEvents(ctx, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAddressEvents", reflect.TypeOf((*MockAddressEventHandler)(nil).HandleAddressEvents), ctx, events)
}

// MockRefreshEventHandler is a mock of RefreshEventHandler interface.
type MockRefreshEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshEventHandlerMockRecorder
	isgomock struct{}
}

// MockRefreshEventHandlerMockRecorder is the mock recorder for MockRefreshEventHandler.
type MockRefreshEventHandlerMockRecorder struct {
	mock *MockRefreshEventHandler
}

// NewMockRefreshEventHandler creates a new mock instance.
func NewMockRefreshEventHandler(ctrl *gomock.Controller) *MockRefreshEventHandler {
	mock := &MockRefreshEventHandler{ctrl: ctrl}
	mock.recorder = &MockRefreshEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshEventHandler) EXPECT() *MockRefreshEventHandlerMockRecorder {
	return m.recorder
}

// HandleRefreshEvent mocks base method.
func (m *MockRefreshEventHandler) HandleRefreshEvent(ctx context.Context, flag proton.RefreshFlag, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleRefreshEvent", ctx, flag, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleRefreshEvent indicates an expected call of HandleRefreshEvent.
func (mr *MockRefreshEventHandlerMockRecorder) HandleRefreshEvent(ctx, flag, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRefreshEvent", reflect.TypeOf((*MockRefreshEventHandler)(nil).HandleRefreshEvent), ctx, flag, eventID)
}

// MockUserEventHandler is a mock of UserEventHandler interface.
type MockUserEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUserEventHandlerMockRecorder
	isgomock struct{}
}

// MockUserEventHandlerMockRecorder is the mock recorder for MockUserEventHandler.
type MockUserEventHandlerMockRecorder struct {
	mock *MockUserEventHandler
}

// NewMockUserEventHandler creates a new mock instance.
func NewMockUserEventHandler(ctrl *gomock.Controller) *MockUserEventHandler {
	mock := &MockUserEventHandler{ctrl: ctrl}
	mock.recorder = &MockUserEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserEventHandler) EXPECT() *MockUserEventHandlerMockRecorder {
	return m.recorder
}

// HandleUserEvent mocks base method.
func (m *MockUserEventHandler) HandleUserEvent(ctx context.Context, user *proton.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUserEvent", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUserEvent indicates an expected call of HandleUserEvent.
func (mr *MockUserEventHandlerMockRecorder) HandleUserEvent(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUserEvent", reflect.TypeOf((*MockUserEventHandler)(nil).HandleUserEvent), ctx, user)
}

// MockUserUsedSpaceEventHandler is a mock of UserUsedSpaceEventHandler interface.
type MockUserUsedSpaceEventHandler struct {
	ctrl     *gomock.Controller
	recorder *MockUserUsedSpaceEventHandlerMockRecorder
	isgomock struct{}
}

// MockUserUsedSpaceEventHandlerMockRecorder is the mock recorder for MockUserUsedSpaceEventHandler.
type MockUserUsedSpaceEventHandlerMockRecorder struct {
	mock *MockUserUsedSpaceEventHandler
}

// NewMockUserUsedSpaceEventHandler creates a new mock instance.
func NewMockUserUsedSpaceEventHandler(ctrl *gomock.Controller) *MockUserUsedSpaceEventHandler {
	mock := &MockUserUsedSpaceEventHandler{ctrl: ctrl}
	mock.recorder = &MockUserUsedSpaceEventHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserUsedSpaceEventHandler) EXPECT() *MockUserUsedSpaceEventHandlerMockRecorder {
	return m.recorder
}

// HandleUsedSpaceEvent mocks base method.
func (m *MockUserUsedSpaceEventHandler) HandleUsedSpaceEvent(ctx context.Context, newSpace int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUsedSpaceEvent", ctx, newSpace)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleUsedSpaceEvent indicates an expected call of HandleUsedSpaceEvent.
func (mr *MockUserUsedSpaceEventHandlerMockRecorder) HandleUsedSpaceEvent(ctx, newSpace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUsedSpaceEvent", reflect.TypeOf((*MockUserUsedSpaceEventHandler)(nil).HandleUsedSpaceEvent), ctx, newSpace)
}
