// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProtonMail/proton-bridge/v3/internal/updater (interfaces: Downloader,Installer)
//
// Generated by this command:
//
//	mockgen --package mocks github.com/ProtonMail/proton-bridge/v3/internal/updater Downloader,Installer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	semver "github.com/Masterminds/semver/v3"
	crypto "github.com/ProtonMail/gopenpgp/v2/crypto"
	gomock "go.uber.org/mock/gomock"
)

// MockDownloader is a mock of Downloader interface.
type MockDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockDownloaderMockRecorder
	isgomock struct{}
}

// MockDownloaderMockRecorder is the mock recorder for MockDownloader.
type MockDownloaderMockRecorder struct {
	mock *MockDownloader
}

// NewMockDownloader creates a new mock instance.
func NewMockDownloader(ctrl *gomock.Controller) *MockDownloader {
	mock := &MockDownloader{ctrl: ctrl}
	mock.recorder = &MockDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloader) EXPECT() *MockDownloaderMockRecorder {
	return m.recorder
}

// DownloadAndVerify mocks base method.
func (m *MockDownloader) DownloadAndVerify(ctx context.Context, kr *crypto.KeyRing, url, sig string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadAndVerify", ctx, kr, url, sig)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadAndVerify indicates an expected call of DownloadAndVerify.
func (mr *MockDownloaderMockRecorder) DownloadAndVerify(ctx, kr, url, sig any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadAndVerify", reflect.TypeOf((*MockDownloader)(nil).DownloadAndVerify), ctx, kr, url, sig)
}

// MockInstaller is a mock of Installer interface.
type MockInstaller struct {
	ctrl     *gomock.Controller
	recorder *MockInstallerMockRecorder
	isgomock struct{}
}

// MockInstallerMockRecorder is the mock recorder for MockInstaller.
type MockInstallerMockRecorder struct {
	mock *MockInstaller
}

// NewMockInstaller creates a new mock instance.
func NewMockInstaller(ctrl *gomock.Controller) *MockInstaller {
	mock := &MockInstaller{ctrl: ctrl}
	mock.recorder = &MockInstallerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInstaller) EXPECT() *MockInstallerMockRecorder {
	return m.recorder
}

// InstallUpdate mocks base method.
func (m *MockInstaller) InstallUpdate(arg0 *semver.Version, arg1 io.Reader, arg2 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InstallUpdate", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// InstallUpdate indicates an expected call of InstallUpdate.
func (mr *MockInstallerMockRecorder) InstallUpdate(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InstallUpdate", reflect.TypeOf((*MockInstaller)(nil).InstallUpdate), arg0, arg1, arg2)
}

// IsAlreadyInstalled mocks base method.
func (m *MockInstaller) IsAlreadyInstalled(arg0 *semver.Version) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAlreadyInstalled", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAlreadyInstalled indicates an expected call of IsAlreadyInstalled.
func (mr *MockInstallerMockRecorder) IsAlreadyInstalled(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAlreadyInstalled", reflect.TypeOf((*MockInstaller)(nil).IsAlreadyInstalled), arg0)
}
