// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProtonMail/proton-bridge/v3/internal/services/syncservice (interfaces: ApplyStageInput,BuildStageInput,BuildStageOutput,DownloadStageInput,DownloadStageOutput,MetadataStageInput,MetadataStageOutput,StateProvider,Regulator,UpdateApplier,MessageBuilder,APIClient,Reporter,DownloadRateModifier)
//
// Generated by this command:
//
//	mockgen --self_package github.com/ProtonMail/proton-bridge/v3/internal/services/syncservice -package syncservice github.com/ProtonMail/proton-bridge/v3/internal/services/syncservice ApplyStageInput,BuildStageInput,BuildStageOutput,DownloadStageInput,DownloadStageOutput,MetadataStageInput,MetadataStageOutput,StateProvider,Regulator,UpdateApplier,MessageBuilder,APIClient,Reporter,DownloadRateModifier
//

// Package syncservice is a generated GoMock package.
package syncservice

import (
	bytes "bytes"
	context "context"
	io "io"
	reflect "reflect"

	proton "github.com/ProtonMail/go-proton-api"
	crypto "github.com/ProtonMail/gopenpgp/v2/crypto"
	gomock "go.uber.org/mock/gomock"
)

// MockApplyStageInput is a mock of ApplyStageInput interface.
type MockApplyStageInput[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockApplyStageInputMockRecorder[T]
	isgomock struct{}
}

// MockApplyStageInputMockRecorder is the mock recorder for MockApplyStageInput.
type MockApplyStageInputMockRecorder[T any] struct {
	mock *MockApplyStageInput[T]
}

// NewMockApplyStageInput creates a new mock instance.
func NewMockApplyStageInput[T any](ctrl *gomock.Controller) *MockApplyStageInput[T] {
	mock := &MockApplyStageInput[T]{ctrl: ctrl}
	mock.recorder = &MockApplyStageInputMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplyStageInput[T]) EXPECT() *MockApplyStageInputMockRecorder[T] {
	return m.recorder
}

// Consume mocks base method.
func (m *MockApplyStageInput[T]) Consume(ctx context.Context) (ApplyRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx)
	ret0, _ := ret[0].(ApplyRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockApplyStageInputMockRecorder[T]) Consume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockApplyStageInput[T])(nil).Consume), ctx)
}

// MockBuildStageInput is a mock of BuildStageInput interface.
type MockBuildStageInput[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockBuildStageInputMockRecorder[T]
	isgomock struct{}
}

// MockBuildStageInputMockRecorder is the mock recorder for MockBuildStageInput.
type MockBuildStageInputMockRecorder[T any] struct {
	mock *MockBuildStageInput[T]
}

// NewMockBuildStageInput creates a new mock instance.
func NewMockBuildStageInput[T any](ctrl *gomock.Controller) *MockBuildStageInput[T] {
	mock := &MockBuildStageInput[T]{ctrl: ctrl}
	mock.recorder = &MockBuildStageInputMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildStageInput[T]) EXPECT() *MockBuildStageInputMockRecorder[T] {
	return m.recorder
}

// Consume mocks base method.
func (m *MockBuildStageInput[T]) Consume(ctx context.Context) (BuildRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx)
	ret0, _ := ret[0].(BuildRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockBuildStageInputMockRecorder[T]) Consume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockBuildStageInput[T])(nil).Consume), ctx)
}

// MockBuildStageOutput is a mock of BuildStageOutput interface.
type MockBuildStageOutput[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockBuildStageOutputMockRecorder[T]
	isgomock struct{}
}

// MockBuildStageOutputMockRecorder is the mock recorder for MockBuildStageOutput.
type MockBuildStageOutputMockRecorder[T any] struct {
	mock *MockBuildStageOutput[T]
}

// NewMockBuildStageOutput creates a new mock instance.
func NewMockBuildStageOutput[T any](ctrl *gomock.Controller) *MockBuildStageOutput[T] {
	mock := &MockBuildStageOutput[T]{ctrl: ctrl}
	mock.recorder = &MockBuildStageOutputMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuildStageOutput[T]) EXPECT() *MockBuildStageOutputMockRecorder[T] {
	return m.recorder
}

// Close mocks base method.
func (m *MockBuildStageOutput[T]) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockBuildStageOutputMockRecorder[T]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBuildStageOutput[T])(nil).Close))
}

// Produce mocks base method.
func (m *MockBuildStageOutput[T]) Produce(ctx context.Context, value ApplyRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockBuildStageOutputMockRecorder[T]) Produce(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockBuildStageOutput[T])(nil).Produce), ctx, value)
}

// MockDownloadStageInput is a mock of DownloadStageInput interface.
type MockDownloadStageInput[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadStageInputMockRecorder[T]
	isgomock struct{}
}

// MockDownloadStageInputMockRecorder is the mock recorder for MockDownloadStageInput.
type MockDownloadStageInputMockRecorder[T any] struct {
	mock *MockDownloadStageInput[T]
}

// NewMockDownloadStageInput creates a new mock instance.
func NewMockDownloadStageInput[T any](ctrl *gomock.Controller) *MockDownloadStageInput[T] {
	mock := &MockDownloadStageInput[T]{ctrl: ctrl}
	mock.recorder = &MockDownloadStageInputMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadStageInput[T]) EXPECT() *MockDownloadStageInputMockRecorder[T] {
	return m.recorder
}

// Consume mocks base method.
func (m *MockDownloadStageInput[T]) Consume(ctx context.Context) (DownloadRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx)
	ret0, _ := ret[0].(DownloadRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockDownloadStageInputMockRecorder[T]) Consume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockDownloadStageInput[T])(nil).Consume), ctx)
}

// MockDownloadStageOutput is a mock of DownloadStageOutput interface.
type MockDownloadStageOutput[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadStageOutputMockRecorder[T]
	isgomock struct{}
}

// MockDownloadStageOutputMockRecorder is the mock recorder for MockDownloadStageOutput.
type MockDownloadStageOutputMockRecorder[T any] struct {
	mock *MockDownloadStageOutput[T]
}

// NewMockDownloadStageOutput creates a new mock instance.
func NewMockDownloadStageOutput[T any](ctrl *gomock.Controller) *MockDownloadStageOutput[T] {
	mock := &MockDownloadStageOutput[T]{ctrl: ctrl}
	mock.recorder = &MockDownloadStageOutputMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadStageOutput[T]) EXPECT() *MockDownloadStageOutputMockRecorder[T] {
	return m.recorder
}

// Close mocks base method.
func (m *MockDownloadStageOutput[T]) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockDownloadStageOutputMockRecorder[T]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDownloadStageOutput[T])(nil).Close))
}

// Produce mocks base method.
func (m *MockDownloadStageOutput[T]) Produce(ctx context.Context, value BuildRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockDownloadStageOutputMockRecorder[T]) Produce(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockDownloadStageOutput[T])(nil).Produce), ctx, value)
}

// MockMetadataStageInput is a mock of MetadataStageInput interface.
type MockMetadataStageInput[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataStageInputMockRecorder[T]
	isgomock struct{}
}

// MockMetadataStageInputMockRecorder is the mock recorder for MockMetadataStageInput.
type MockMetadataStageInputMockRecorder[T any] struct {
	mock *MockMetadataStageInput[T]
}

// NewMockMetadataStageInput creates a new mock instance.
func NewMockMetadataStageInput[T any](ctrl *gomock.Controller) *MockMetadataStageInput[T] {
	mock := &MockMetadataStageInput[T]{ctrl: ctrl}
	mock.recorder = &MockMetadataStageInputMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataStageInput[T]) EXPECT() *MockMetadataStageInputMockRecorder[T] {
	return m.recorder
}

// Consume mocks base method.
func (m *MockMetadataStageInput[T]) Consume(ctx context.Context) (*Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx)
	ret0, _ := ret[0].(*Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockMetadataStageInputMockRecorder[T]) Consume(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockMetadataStageInput[T])(nil).Consume), ctx)
}

// MockMetadataStageOutput is a mock of MetadataStageOutput interface.
type MockMetadataStageOutput[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataStageOutputMockRecorder[T]
	isgomock struct{}
}

// MockMetadataStageOutputMockRecorder is the mock recorder for MockMetadataStageOutput.
type MockMetadataStageOutputMockRecorder[T any] struct {
	mock *MockMetadataStageOutput[T]
}

// NewMockMetadataStageOutput creates a new mock instance.
func NewMockMetadataStageOutput[T any](ctrl *gomock.Controller) *MockMetadataStageOutput[T] {
	mock := &MockMetadataStageOutput[T]{ctrl: ctrl}
	mock.recorder = &MockMetadataStageOutputMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataStageOutput[T]) EXPECT() *MockMetadataStageOutputMockRecorder[T] {
	return m.recorder
}

// Close mocks base method.
func (m *MockMetadataStageOutput[T]) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMetadataStageOutputMockRecorder[T]) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMetadataStageOutput[T])(nil).Close))
}

// Produce mocks base method.
func (m *MockMetadataStageOutput[T]) Produce(ctx context.Context, value DownloadRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", ctx, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce.
func (mr *MockMetadataStageOutputMockRecorder[T]) Produce(ctx, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockMetadataStageOutput[T])(nil).Produce), ctx, value)
}

// MockStateProvider is a mock of StateProvider interface.
type MockStateProvider struct {
	ctrl     *gomock.Controller
	recorder *MockStateProviderMockRecorder
	isgomock struct{}
}

// MockStateProviderMockRecorder is the mock recorder for MockStateProvider.
type MockStateProviderMockRecorder struct {
	mock *MockStateProvider
}

// NewMockStateProvider creates a new mock instance.
func NewMockStateProvider(ctrl *gomock.Controller) *MockStateProvider {
	mock := &MockStateProvider{ctrl: ctrl}
	mock.recorder = &MockStateProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateProvider) EXPECT() *MockStateProviderMockRecorder {
	return m.recorder
}

// AddFailedMessageID mocks base method.
func (m *MockStateProvider) AddFailedMessageID(arg0 context.Context, arg1 ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddFailedMessageID", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddFailedMessageID indicates an expected call of AddFailedMessageID.
func (mr *MockStateProviderMockRecorder) AddFailedMessageID(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFailedMessageID", reflect.TypeOf((*MockStateProvider)(nil).AddFailedMessageID), varargs...)
}

// ClearSyncStatus mocks base method.
func (m *MockStateProvider) ClearSyncStatus(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSyncStatus", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSyncStatus indicates an expected call of ClearSyncStatus.
func (mr *MockStateProviderMockRecorder) ClearSyncStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSyncStatus", reflect.TypeOf((*MockStateProvider)(nil).ClearSyncStatus), arg0)
}

// GetSyncStatus mocks base method.
func (m *MockStateProvider) GetSyncStatus(arg0 context.Context) (Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSyncStatus", arg0)
	ret0, _ := ret[0].(Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSyncStatus indicates an expected call of GetSyncStatus.
func (mr *MockStateProviderMockRecorder) GetSyncStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSyncStatus", reflect.TypeOf((*MockStateProvider)(nil).GetSyncStatus), arg0)
}

// RemFailedMessageID mocks base method.
func (m *MockStateProvider) RemFailedMessageID(arg0 context.Context, arg1 ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RemFailedMessageID", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemFailedMessageID indicates an expected call of RemFailedMessageID.
func (mr *MockStateProviderMockRecorder) RemFailedMessageID(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemFailedMessageID", reflect.TypeOf((*MockStateProvider)(nil).RemFailedMessageID), varargs...)
}

// SetHasLabels mocks base method.
func (m *MockStateProvider) SetHasLabels(arg0 context.Context, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHasLabels", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHasLabels indicates an expected call of SetHasLabels.
func (mr *MockStateProviderMockRecorder) SetHasLabels(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasLabels", reflect.TypeOf((*MockStateProvider)(nil).SetHasLabels), arg0, arg1)
}

// SetHasMessages mocks base method.
func (m *MockStateProvider) SetHasMessages(arg0 context.Context, arg1 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHasMessages", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHasMessages indicates an expected call of SetHasMessages.
func (mr *MockStateProviderMockRecorder) SetHasMessages(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasMessages", reflect.TypeOf((*MockStateProvider)(nil).SetHasMessages), arg0, arg1)
}

// SetLastMessageID mocks base method.
func (m *MockStateProvider) SetLastMessageID(arg0 context.Context, arg1 string, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastMessageID", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastMessageID indicates an expected call of SetLastMessageID.
func (mr *MockStateProviderMockRecorder) SetLastMessageID(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastMessageID", reflect.TypeOf((*MockStateProvider)(nil).SetLastMessageID), arg0, arg1, arg2)
}

// SetMessageCount mocks base method.
func (m *MockStateProvider) SetMessageCount(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMessageCount", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMessageCount indicates an expected call of SetMessageCount.
func (mr *MockStateProviderMockRecorder) SetMessageCount(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMessageCount", reflect.TypeOf((*MockStateProvider)(nil).SetMessageCount), arg0, arg1)
}

// MockRegulator is a mock of Regulator interface.
type MockRegulator struct {
	ctrl     *gomock.Controller
	recorder *MockRegulatorMockRecorder
	isgomock struct{}
}

// MockRegulatorMockRecorder is the mock recorder for MockRegulator.
type MockRegulatorMockRecorder struct {
	mock *MockRegulator
}

// NewMockRegulator creates a new mock instance.
func NewMockRegulator(ctrl *gomock.Controller) *MockRegulator {
	mock := &MockRegulator{ctrl: ctrl}
	mock.recorder = &MockRegulatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegulator) EXPECT() *MockRegulatorMockRecorder {
	return m.recorder
}

// Sync mocks base method.
func (m *MockRegulator) Sync(ctx context.Context, stage *Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, stage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockRegulatorMockRecorder) Sync(ctx, stage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockRegulator)(nil).Sync), ctx, stage)
}

// MockUpdateApplier is a mock of UpdateApplier interface.
type MockUpdateApplier struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateApplierMockRecorder
	isgomock struct{}
}

// MockUpdateApplierMockRecorder is the mock recorder for MockUpdateApplier.
type MockUpdateApplierMockRecorder struct {
	mock *MockUpdateApplier
}

// NewMockUpdateApplier creates a new mock instance.
func NewMockUpdateApplier(ctrl *gomock.Controller) *MockUpdateApplier {
	mock := &MockUpdateApplier{ctrl: ctrl}
	mock.recorder = &MockUpdateApplierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateApplier) EXPECT() *MockUpdateApplierMockRecorder {
	return m.recorder
}

// ApplySyncUpdates mocks base method.
func (m *MockUpdateApplier) ApplySyncUpdates(ctx context.Context, updates []BuildResult) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplySyncUpdates", ctx, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplySyncUpdates indicates an expected call of ApplySyncUpdates.
func (mr *MockUpdateApplierMockRecorder) ApplySyncUpdates(ctx, updates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplySyncUpdates", reflect.TypeOf((*MockUpdateApplier)(nil).ApplySyncUpdates), ctx, updates)
}

// SyncLabels mocks base method.
func (m *MockUpdateApplier) SyncLabels(ctx context.Context, labels map[string]proton.Label) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncLabels", ctx, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// SyncLabels indicates an expected call of SyncLabels.
func (mr *MockUpdateApplierMockRecorder) SyncLabels(ctx, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncLabels", reflect.TypeOf((*MockUpdateApplier)(nil).SyncLabels), ctx, labels)
}

// MockMessageBuilder is a mock of MessageBuilder interface.
type MockMessageBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockMessageBuilderMockRecorder
	isgomock struct{}
}

// MockMessageBuilderMockRecorder is the mock recorder for MockMessageBuilder.
type MockMessageBuilderMockRecorder struct {
	mock *MockMessageBuilder
}

// NewMockMessageBuilder creates a new mock instance.
func NewMockMessageBuilder(ctrl *gomock.Controller) *MockMessageBuilder {
	mock := &MockMessageBuilder{ctrl: ctrl}
	mock.recorder = &MockMessageBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageBuilder) EXPECT() *MockMessageBuilderMockRecorder {
	return m.recorder
}

// BuildMessage mocks base method.
func (m *MockMessageBuilder) BuildMessage(apiLabels map[string]proton.Label, full proton.FullMessage, addrKR *crypto.KeyRing, buffer *bytes.Buffer) (BuildResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildMessage", apiLabels, full, addrKR, buffer)
	ret0, _ := ret[0].(BuildResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildMessage indicates an expected call of BuildMessage.
func (mr *MockMessageBuilderMockRecorder) BuildMessage(apiLabels, full, addrKR, buffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildMessage", reflect.TypeOf((*MockMessageBuilder)(nil).BuildMessage), apiLabels, full, addrKR, buffer)
}

// WithKeys mocks base method.
func (m *MockMessageBuilder) WithKeys(f func(*crypto.KeyRing, map[string]*crypto.KeyRing) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithKeys", f)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithKeys indicates an expected call of WithKeys.
func (mr *MockMessageBuilderMockRecorder) WithKeys(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithKeys", reflect.TypeOf((*MockMessageBuilder)(nil).WithKeys), f)
}

// MockAPIClient is a mock of APIClient interface.
type MockAPIClient struct {
	ctrl     *gomock.Controller
	recorder *MockAPIClientMockRecorder
	isgomock struct{}
}

// MockAPIClientMockRecorder is the mock recorder for MockAPIClient.
type MockAPIClientMockRecorder struct {
	mock *MockAPIClient
}

// NewMockAPIClient creates a new mock instance.
func NewMockAPIClient(ctrl *gomock.Controller) *MockAPIClient {
	mock := &MockAPIClient{ctrl: ctrl}
	mock.recorder = &MockAPIClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPIClient) EXPECT() *MockAPIClientMockRecorder {
	return m.recorder
}

// GetAttachment mocks base method.
func (m *MockAPIClient) GetAttachment(ctx context.Context, attachmentID string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachment", ctx, attachmentID)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttachment indicates an expected call of GetAttachment.
func (mr *MockAPIClientMockRecorder) GetAttachment(ctx, attachmentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachment", reflect.TypeOf((*MockAPIClient)(nil).GetAttachment), ctx, attachmentID)
}

// GetAttachmentInto mocks base method.
func (m *MockAPIClient) GetAttachmentInto(ctx context.Context, attachmentID string, reader io.ReaderFrom) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentInto", ctx, attachmentID, reader)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAttachmentInto indicates an expected call of GetAttachmentInto.
func (mr *MockAPIClientMockRecorder) GetAttachmentInto(ctx, attachmentID, reader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentInto", reflect.TypeOf((*MockAPIClient)(nil).GetAttachmentInto), ctx, attachmentID, reader)
}

// GetFullMessage mocks base method.
func (m *MockAPIClient) GetFullMessage(ctx context.Context, messageID string, scheduler proton.Scheduler, storageProvider proton.AttachmentAllocator) (proton.FullMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullMessage", ctx, messageID, scheduler, storageProvider)
	ret0, _ := ret[0].(proton.FullMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullMessage indicates an expected call of GetFullMessage.
func (mr *MockAPIClientMockRecorder) GetFullMessage(ctx, messageID, scheduler, storageProvider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullMessage", reflect.TypeOf((*MockAPIClient)(nil).GetFullMessage), ctx, messageID, scheduler, storageProvider)
}

// GetGroupedMessageCount mocks base method.
func (m *MockAPIClient) GetGroupedMessageCount(ctx context.Context) ([]proton.MessageGroupCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupedMessageCount", ctx)
	ret0, _ := ret[0].([]proton.MessageGroupCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupedMessageCount indicates an expected call of GetGroupedMessageCount.
func (mr *MockAPIClientMockRecorder) GetGroupedMessageCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupedMessageCount", reflect.TypeOf((*MockAPIClient)(nil).GetGroupedMessageCount), ctx)
}

// GetLabels mocks base method.
func (m *MockAPIClient) GetLabels(ctx context.Context, labelTypes ...proton.LabelType) ([]proton.Label, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range labelTypes {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLabels", varargs...)
	ret0, _ := ret[0].([]proton.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockAPIClientMockRecorder) GetLabels(ctx any, labelTypes ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, labelTypes...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockAPIClient)(nil).GetLabels), varargs...)
}

// GetMessage mocks base method.
func (m *MockAPIClient) GetMessage(ctx context.Context, messageID string) (proton.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, messageID)
	ret0, _ := ret[0].(proton.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockAPIClientMockRecorder) GetMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockAPIClient)(nil).GetMessage), ctx, messageID)
}

// GetMessageMetadataPage mocks base method.
func (m *MockAPIClient) GetMessageMetadataPage(ctx context.Context, page, pageSize int, filter proton.MessageFilter) ([]proton.MessageMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageMetadataPage", ctx, page, pageSize, filter)
	ret0, _ := ret[0].([]proton.MessageMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageMetadataPage indicates an expected call of GetMessageMetadataPage.
func (mr *MockAPIClientMockRecorder) GetMessageMetadataPage(ctx, page, pageSize, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageMetadataPage", reflect.TypeOf((*MockAPIClient)(nil).GetMessageMetadataPage), ctx, page, pageSize, filter)
}

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// InitializeProgressCounter mocks base method.
func (m *MockReporter) InitializeProgressCounter(ctx context.Context, current, total int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InitializeProgressCounter", ctx, current, total)
}

// InitializeProgressCounter indicates an expected call of InitializeProgressCounter.
func (mr *MockReporterMockRecorder) InitializeProgressCounter(ctx, current, total any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitializeProgressCounter", reflect.TypeOf((*MockReporter)(nil).InitializeProgressCounter), ctx, current, total)
}

// OnError mocks base method.
func (m *MockReporter) OnError(ctx context.Context, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnError", ctx, err)
}

// OnError indicates an expected call of OnError.
func (mr *MockReporterMockRecorder) OnError(ctx, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnError", reflect.TypeOf((*MockReporter)(nil).OnError), ctx, err)
}

// OnFinished mocks base method.
func (m *MockReporter) OnFinished(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnFinished", ctx)
}

// OnFinished indicates an expected call of OnFinished.
func (mr *MockReporterMockRecorder) OnFinished(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnFinished", reflect.TypeOf((*MockReporter)(nil).OnFinished), ctx)
}

// OnProgress mocks base method.
func (m *MockReporter) OnProgress(ctx context.Context, delta int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnProgress", ctx, delta)
}

// OnProgress indicates an expected call of OnProgress.
func (mr *MockReporterMockRecorder) OnProgress(ctx, delta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnProgress", reflect.TypeOf((*MockReporter)(nil).OnProgress), ctx, delta)
}

// OnStart mocks base method.
func (m *MockReporter) OnStart(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnStart", ctx)
}

// OnStart indicates an expected call of OnStart.
func (mr *MockReporterMockRecorder) OnStart(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnStart", reflect.TypeOf((*MockReporter)(nil).OnStart), ctx)
}

// MockDownloadRateModifier is a mock of DownloadRateModifier interface.
type MockDownloadRateModifier struct {
	ctrl     *gomock.Controller
	recorder *MockDownloadRateModifierMockRecorder
	isgomock struct{}
}

// MockDownloadRateModifierMockRecorder is the mock recorder for MockDownloadRateModifier.
type MockDownloadRateModifierMockRecorder struct {
	mock *MockDownloadRateModifier
}

// NewMockDownloadRateModifier creates a new mock instance.
func NewMockDownloadRateModifier(ctrl *gomock.Controller) *MockDownloadRateModifier {
	mock := &MockDownloadRateModifier{ctrl: ctrl}
	mock.recorder = &MockDownloadRateModifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownloadRateModifier) EXPECT() *MockDownloadRateModifierMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockDownloadRateModifier) Apply(wasSuccess bool, currentValue, maxValue int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", wasSuccess, currentValue, maxValue)
	ret0, _ := ret[0].(int)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockDownloadRateModifierMockRecorder) Apply(wasSuccess, currentValue, maxValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockDownloadRateModifier)(nil).Apply), wasSuccess, currentValue, maxValue)
}
